type Qrcode = {
  name: string;
  code: string;
  description: string;
  costPrice: number;
  sellingPrice: number;
  createdAt: Date;
};
export const qrCodes: Qrcode[] = [
  {
    name: "Apple iPhone 14",
    code: "QRIPH14",
    description: "Apple iPhone 14 - 128GB Midnight",
    costPrice: 799,
    sellingPrice: 899,
    createdAt: new Date("2025-01-15"),
  },
  {
    name: "Samsung Galaxy S23",
    code: "QRSAM23",
    description: "Samsung Galaxy S23 - 256GB Phantom Black",
    costPrice: 749,
    sellingPrice: 849,
    createdAt: new Date("2025-01-20"),
  },
  {
    name: "Sony WH-1000XM5",
    code: "QRSONYXM5",
    description: "Sony Noise Cancelling Headphones WH-1000XM5",
    costPrice: 299,
    sellingPrice: 349,
    createdAt: new Date("2025-02-01"),
  },
  {
    name: "Dell XPS 15",
    code: "QRXPS15",
    description: "Dell XPS 15 Laptop - Intel i7, 16GB RAM, 512GB SSD",
    costPrice: 1299,
    sellingPrice: 1499,
    createdAt: new Date("2025-01-10"),
  },
  {
    name: "Logitech MX Master 3S",
    code: "QRLOGIMX3S",
    description: "Logitech MX Master 3S Advanced Wireless Mouse",
    costPrice: 89,
    sellingPrice: 99,
    createdAt: new Date("2025-02-05"),
  },
  {
    name: "MacBook Air M2",
    code: "QRMBAM2",
    description: "Apple MacBook Air M2 Chip, 8GB RAM, 256GB SSD",
    costPrice: 999,
    sellingPrice: 1099,
    createdAt: new Date("2025-01-25"),
  },
  {
    name: "Nintendo Switch OLED",
    code: "QRNSOLED",
    description: "Nintendo Switch OLED Model - White",
    costPrice: 299,
    sellingPrice: 349,
    createdAt: new Date("2025-02-10"),
  },
  {
    name: "Bose QuietComfort 45",
    code: "QRBOSEQC45",
    description: "Bose QuietComfort 45 Wireless Headphones",
    costPrice: 249,
    sellingPrice: 299,
    createdAt: new Date("2025-01-30"),
  },
  {
    name: "Sony PlayStation 5",
    code: "QRPS5",
    description: "Sony PlayStation 5 - Disc Edition",
    costPrice: 499,
    sellingPrice: 549,
    createdAt: new Date("2025-02-15"),
  },
  {
    name: "Google Pixel 7 Pro",
    code: "QRPIXEL7P",
    description: "Google Pixel 7 Pro - 128GB Snow",
    costPrice: 799,
    sellingPrice: 899,
    createdAt: new Date("2025-01-18"),
  },
  {
    name: "Apple Watch Series 8",
    code: "QRAW8",
    description: "Apple Watch Series 8 GPS - 41mm Midnight",
    costPrice: 399,
    sellingPrice: 429,
    createdAt: new Date("2025-02-08"),
  },
  {
    name: "Razer DeathAdder V3 Pro",
    code: "QRRZDA3P",
    description: "Razer DeathAdder V3 Pro Wireless Gaming Mouse",
    costPrice: 129,
    sellingPrice: 149,
    createdAt: new Date("2025-02-12"),
  },
  {
    name: "Samsung 980 Pro SSD",
    code: "QRSAMS980",
    description: "Samsung 980 Pro 1TB NVMe SSD",
    costPrice: 149,
    sellingPrice: 179,
    createdAt: new Date("2025-01-27"),
  },
  {
    name: "GoPro HERO11 Black",
    code: "QRGPH11B",
    description: "GoPro HERO11 Black Action Camera",
    costPrice: 399,
    sellingPrice: 449,
    createdAt: new Date("2025-02-18"),
  },
  {
    name: "Microsoft Surface Pro 9",
    code: "QRMSP9",
    description: "Microsoft Surface Pro 9 - Intel i5, 8GB RAM, 256GB SSD",
    costPrice: 1099,
    sellingPrice: 1199,
    createdAt: new Date("2025-01-12"),
  },
  {
    name: "Corsair K100 RGB",
    code: "QRCORK100",
    description: "Corsair K100 RGB Mechanical Gaming Keyboard",
    costPrice: 199,
    sellingPrice: 229,
    createdAt: new Date("2025-02-20"),
  },
  {
    name: "Amazon Kindle Paperwhite",
    code: "QRKINDLEPW",
    description: "Amazon Kindle Paperwhite 11th Gen",
    costPrice: 129,
    sellingPrice: 149,
    createdAt: new Date("2025-02-14"),
  },
  {
    name: "DJI Mini 3 Pro",
    code: "QRDJIM3P",
    description: "DJI Mini 3 Pro Drone with Smart Controller",
    costPrice: 749,
    sellingPrice: 849,
    createdAt: new Date("2025-01-22"),
  },
  {
    name: "HyperX Cloud Alpha Wireless",
    code: "QRHXCAW",
    description: "HyperX Cloud Alpha Wireless Gaming Headset",
    costPrice: 149,
    sellingPrice: 179,
    createdAt: new Date("2025-02-22"),
  },
];
